### ISSUE TITLE
K8S: Modify sysctl values like fs.inotify.max_user_watches

### ISSUE THREAD

**Issue by gbhrdt** [ovh/public-cloud-roadmap#326]
In our Managed Kubernetes clusters we are currently unable to modify sysctl values like `fs.inotify.max_user_watches` but those are needed for our containers, as they are watching > 8192 files (default limit).

**Comment by gbhrdt** [comment]
I was able to make it work with an init container, my bad.

```
- name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - fs.inotify.max_user_watches=262144
        securityContext:
          privileged: true


```
